### ISSUE TITLE
interface nested in object fail in union

### ISSUE THREAD

**Issue by lxcid** [ianstormtaylor/superstruct#119]
I found a case that I believe should succeed but failed… I haven't had a chance to dig too deep into why yet but I'm filling the issue here to share my finding. :)

I wrote a fixture for testing union of structs:

```js
import { struct } from '../../..'

export const Struct = struct({
  name: 'string',
  age: 'number',
  address: struct.union([
    // This will fail…
    struct.object({
      foo: struct.interface({
        street: 'string',
        city: 'string',
        state: 'string',
        zipcode: 'string',
        country: struct.literal('United States of America'),
      }),
    }),
    /*
    // This would work…
    struct.interface({
      street: 'string',
      city: 'string',
      state: 'string',
      zipcode: 'string',
      country: struct.literal('United States of America'),
    }),
    */
    // If this is place before the first schema, it will work as well…
    struct.object({
      street: 'string',
      city: 'string',
      postcode: 'string',
      country: struct.literal('Singapore'),
    }),
  ]),
})

export const data = {
  name: 'john',
  age: 42,
  address: {
    street: 'Woodlands Street 42',
    city: 'Woodlands',
    postcode: '123456',
    country: 'Singapore',
  },
}

export const output = {
  name: 'john',
  age: 42,
  address: {
    street: 'Woodlands Street 42',
    city: 'Woodlands',
    postcode: '123456',
    country: 'Singapore',
  },
}
```

This will fail with the following error:

```
     TypeError: Cannot read property 'street' of undefined
      at Kind.validate (lib/index.js:543:15)
      at keys.forEach.key (lib/index.js:752:27)
      at Set.forEach (<anonymous>)
      at Kind.validate (lib/index.js:737:10)
      at Kind.validate (lib/index.js:1011:24)
      at keys.forEach.key (lib/index.js:752:27)
      at Set.forEach (<anonymous>)
      at Kind.validate (lib/index.js:737:10)
      at Function.Struct.assert.value [as assert] (lib/index.js:1178:36)
      at Struct (lib/index.js:1165:21)
      at Context.run (test/index.js:32:28)
```

It seems like having a schema with interface nested in object, nested in a union (like above) and it definition come before others schema to be union'ed, will cause the above failure… Note the ordering of schema definition is important…

```js
struct.union([
  struct.object({
    key: struct.interface({
      ...
    })
  }),
  ...
])
```

**Comment by sanrodari** [comment]
@ianstormtaylor 

Isolated test case:

```js
'use strict';

const { struct } = require('superstruct');

const ExampleStruct = struct.partial({
  id: 'string',
  attributes: struct.interface({
    attr1: 'string',
    attr2: 'string',
  }),
});

ExampleStruct({ id: '123' });
```

```
╰─$ grep superstruct yarn.lock -C 1

superstruct@^0.6.1:
  version "0.6.1"
--
--
  version "0.6.1"
  resolved "https://registry.yarnpkg.com/superstruct/-/superstruct-0.6.1.tgz#148fc3d627bb59fcfe24aa1bd2a1b8c51b1db072"
  integrity sha512-LDbOKL5sNbOJ00Q36iYRhSexKIptZje0/mhNznnz04wT9CmsPDZg/K/UV1dgYuCwNMuOBHTbVROZsGB9EhhK4w==

╰─$ node -v                                                                                                        1 ↵
v10.15.3

╰─$ node server/modules/bug.js
/Users/sanrodari/moove-it/node_modules/superstruct/lib/index.js:543
      let v = value[key];
                   ^

TypeError: Cannot read property 'attr1' of undefined
    at Kind.validate (/Users/sanrodari/moove-it/node_modules/superstruct/lib/index.js:543:20)
    at Kind.validate (/Users/sanrodari/moove-it/node_modules/superstruct/lib/index.js:885:27)
    at Function.Struct.assert.value [as assert] (/Users/sanrodari/moove-it/node_modules/superstruct/lib/index.js:1221:36)
    at Struct (/Users/sanrodari/moove-it/node_modules/superstruct/lib/index.js:1208:21)
    at Object.<anonymous> (/Users/sanrodari/moove-it/server/modules/bug.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by sanrodari** [comment]
Runnable example:

https://repl.it/repls/LonelyWatchfulCareware

**Comment by rmtracey** [comment]
Similar issue here. I have an interface nested within an object. If the object I'm trying to validate is missing the key for the interface, superstruct will fail with the `TypeError: Cannot read property 'x' of undefined` error. It works fine if I replace the interface with a partial.

Simple example:
```javascript
import { struct } from 'superstruct';

const schema = struct({
  foo: 'string',
  bar: struct.interface({
    baz: 'string',
  }),
});

schema.validate({ foo: 'test' });
```
