### ISSUE TITLE
Email validation example didn't work....

### ISSUE THREAD

**Issue by chainhead** [ianstormtaylor/superstruct#439]
I wrote the following (from [here](https://github.com/ianstormtaylor/superstruct/blob/master/docs/guide.md#defining-custom-data-types)) as `v.js` and ran it as `node v.js`. 

```js
import { struct } from 'superstruct'
import isEmail from 'is-email'

const Email = struct('Email', (value) => isEmail(value))

const User = object({
  id: number(),
  name: string(),
  email: email(),
  is_admin: optional(boolean()),
})

const data = {
  id: 43,
  name: 'Jane Smith',
  email: 'jane',
}

assert(data, User)
```

I get an error as follows.

```bash
(function (exports, require, module, __filename, __dirname) { import { struct } from 'superstruct'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Comment by blimmer** [comment]
Hey @chainhead the error message you're getting is because the examples show [ES6-style imports](https://codeburst.io/understanding-es6-modules-import-export-syntax-in-javascript-6c01f20cead3), which are common in TypeScript.

For your use-case, you can use `require` like this:

```js
const { struct, object, number, string, optional, boolean, assert } = require('superstruct');
const isEmail = require('is-email');

const Email = struct('Email', (value) => isEmail(value))

const User = object({
  id: number(),
  name: string(),
  email: Email,
  is_admin: optional(boolean()),
})

const data = {
  id: 43,
  name: 'Jane Smith',
  email: 'jane',
}

assert(data, User)
```

```console
 17:46:14  /tmp/foo  node index.js
/private/tmp/foo/node_modules/superstruct/lib/index.cjs:170
    throw result[0];
    ^

Error
    at new StructError (/private/tmp/foo/node_modules/superstruct/lib/index.cjs:157:18)
    at validate (/private/tmp/foo/node_modules/superstruct/lib/index.cjs:203:19)
    at assert (/private/tmp/foo/node_modules/superstruct/lib/index.cjs:167:18)
    at Object.<anonymous> (/private/tmp/foo/index.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  value: 'jane',
  type: 'Email',
  path: [ 'email' ],
  branch: [ { id: 43, name: 'Jane Smith', email: 'jane' }, 'jane' ],
  failures: [GeneratorFunction: failures]
```
