### ISSUE TITLE
Error building minified UMD bundle

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/superstruct#69]
Following error is encountered when installing superstruct from ground.

Environment: macOS 10.13 / Node V8.3.0

```
➜  superstruct git:(master) npm i
✔ Installed 29 packages
✔ Linked 441 latest versions
[fsevents] Success: "/Users/ewind/code/playground/superstruct/node_modules/_fsevents@1.1.3@fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
✔ Run 1 scripts
yarn run v1.0.2
$ yarn run build:es && yarn run build:cjs && yarn run build:max && yarn run build:min

./src/index.js → ./lib/index.es.js...
created ./lib/index.es.js in 694ms

./src/index.js → ./lib/index.js...
created ./lib/index.js in 1.2s

./src/index.js → ./umd/superstruct.js...
created ./umd/superstruct.js in 821ms
/bin/sh: uglifyjs: command not found

./src/index.js → stdout...
created stdout in 1.1s
Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:862:14)
error Command failed with exit code 127.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ Install fail! Error: Run "sh -c yarn run build" error, exit code 1
Error: Run "sh -c yarn run build" error, exit code 1
    at ChildProcess.proc.on.code (/Users/ewind/.nvm/versions/node/v8.3.0/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

This error message can be tracked to the `build:min` script in package.json:

```
"build:min": "NODE_ENV=production rollup --config ./config/rollup-umd-min.js | uglifyjs > ./umd/superstruct.min.js",
```

This also results in error running `yarn run build`:

```
➜  superstruct git:(fix-build) yarn run build
yarn run v1.0.2
$ yarn run build:es && yarn run build:cjs && yarn run build:max && yarn run build:min

./src/index.js → ./lib/index.es.js...
created ./lib/index.es.js in 637ms

./src/index.js → ./lib/index.js...
created ./lib/index.js in 613ms

./src/index.js → ./umd/superstruct.js...
created ./umd/superstruct.js in 582ms
/bin/sh: uglifyify: command not found

./src/index.js → stdout...
created stdout in 619ms
Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:862:14)
error Command failed with exit code 127.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The `uglifyify` dependency is missing `bin` entry, leading error for npm scripts. I've raised an [issue](https://github.com/hughsk/uglifyify/issues/82) about this, while I suggest a minify config with rollup plugin can work better with less verbose config. I'm going to PR for it 😀

**Comment by ianstormtaylor** [comment]
Wow, good call haha. Looks like I forgot to migrate that, thanks for catching this @doodlewind. I think the `uglifyjs` isn't actually supposed to be with `uglifyify`, but it was with the old `uglify-js` dependency from Slate, but it must have gotten removed by accident haha.
